# Generated by Django 4.2.6 on 2023-10-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0016_history_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhistory',
            name='dynamic_field_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalhistory',
            name='dynamic_field_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='dynamic_field_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='history',
            name='dynamic_field_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
