# Generated by Django 4.2.6 on 2023-10-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0017_historicalhistory_dynamic_field_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhistory',
            name='dynamic_field_1',
        ),
        migrations.RemoveField(
            model_name='historicalhistory',
            name='dynamic_field_2',
        ),
        migrations.RemoveField(
            model_name='history',
            name='dynamic_field_1',
        ),
        migrations.RemoveField(
            model_name='history',
            name='dynamic_field_2',
        ),
    ]
